version: '3.3'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'app'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'secret'
      MYSQL_ROOT_PASSWORD: 'secret'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - db-data:/var/lib/mysql
  verdaccio:
    image: verdaccio/verdaccio
    container_name: verdaccio
    ports:
      - '4873:4873'
    volumes:
      - verdaccio-data:/verdaccio/storage

volumes:
  db-data:
  verdaccio-data:
